export default {
    en: {
        addToCart: 'Add to cart',
        crossSell: 'More in this collection',
        descriptionLabel: 'Description',
        homepage: 'Homepage',
        outOfStock: 'Out of Stock',
        productsList: 'Products',
        quantity: 'Quantity',
        quantityFotocopias: 'Quantity',
        comments: 'Comentarios',
        filestitle: 'Subi el archivo a imprimir (un archivo por pedido)',
        anillado: 'Anillado (+$35)',
        fieldRequired: 'This field is required',
        pagetype: 'Tipo de hoja',
        pagesnum: 'Cantidad de hojas del archivo (Número preciso para calcular el precio a pagar)',
        oficio: 'Hoja oficio',
        a4: 'Hoja A4',
        doblefaz: 'Doble Faz',
        suscribirse: 'Comprar y Suscribirse',
        desuscribirse: 'Desuscribirse',
        login: 'Login',
        register: 'Register',
        cancel: 'Cancel',
        checkout: 'Finalizar',
        continueShopping: 'Continuar comprando',
        registerModalTitle: 'Para ingresar a la lista de grupos de compradores debes ingresar a tu cuenta.',
        thanksModalText: 'Estas suscripto. Ahora rellenaras la informacion de pago y envio. Gracias por la confianza!',
        anotadoModalTitle: 'Anotado!',
        new: 'Crear grupo',
        newModalTitle: 'Add new group',
    },
    es: {
        addToCart: 'Comprar',
        crossSell: 'Otros productos de esta colección',
        descriptionLabel: 'Descripción',
        homepage: 'Página Principal',
        outOfStock: 'Sin Stock',
        productsList: 'Productos',
        quantity: 'Cantidad',
        quantityFotocopias: 'Cant. de juegos',
        filestitle: 'Subi el archivo a imprimir (un archivo por pedido)',
        anillado: 'Anillado (+$35)',
        fieldRequired: 'Este campo es obligatorio',
        comments: 'Comentarios',
        pagetype: 'Tipo de hoja',
        pagesnum: 'Cantidad de hojas del archivo (Número preciso para calcular el precio a pagar)',
        oficio: 'Hoja oficio',
        a4: 'Hoja A4',
        doblefaz: 'Doble Faz',
        suscribirse: 'Comprar y Suscribirse',
        desuscribirse: 'Desuscribirse',
        login: 'Loggearse',
        register: 'Registrarse',
        cancel: 'Cancelar',
        checkout: 'Finalizar',
        continueShopping: 'Continuar comprando',
        registerModalTitle: 'Para ingresar a la lista de grupos de compradores debes ingresar a tu cuenta.',
        anotadoModalTitle: 'Suscripto!',
        thanksModalText: 'Estas suscripto. Ahora rellenarás la información de pago y envío. Gracias por la confianza!',
        new: 'Crear grupo',
        newModalTitle: 'Crear nuevo grupo',
    }
};
